### PR TITLE
fix: panic - waitGroup counter goes negative

### LINKED ISSUE #4099: panic: sync: negative WaitGroup counter
### 🔍 Check for existing issues

- [x] Completed

### How is Dozzle deployed?

Standalone Deployment

### 📦 Dozzle version

8.13.11

### ✅ Command used to run Dozzle

`docker run --name=dozzle -v /var/run/docker.sock:/var/run/docker.sock -d -p 8888:8080 amir20/dozzle --enable-actions --enable-shell`

### 🐛 Describe the bug / provide steps to reproduce it

I was accidentally attaching to a stopped container using the menu in top left. Then I exited the attach container side panel (which pops up when clicking on that menu item). Thats it, dozzle stops. Attaching the dozzle container logs at that time.

1. Try attaching to any stopped container.
2. Close the side panel that pops up
3. Dozzle exits

### 💻 Environment

Client:
 Version:    28.3.2
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  ai: Docker AI Agent - Ask Gordon (Docker Inc.)
    Version:  v1.6.0
    Path:     /Users/akash/.docker/cli-plugins/docker-ai
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.25.0-desktop.1
    Path:     /Users/akash/.docker/cli-plugins/docker-buildx
  cloud: Docker Cloud (Docker Inc.)
    Version:  v0.4.2
    Path:     /Users/akash/.docker/cli-plugins/docker-cloud
  compose: Docker Compose (Docker Inc.)
    Version:  v2.38.2-desktop.1
    Path:     /Users/akash/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.41
    Path:     /Users/akash/.docker/cli-plugins/docker-debug
  desktop: Docker Desktop commands (Docker Inc.)
    Version:  v0.1.11
    Path:     /Users/akash/.docker/cli-plugins/docker-desktop
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.29
    Path:     /Users/akash/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.4.0
    Path:     /Users/akash/.docker/cli-plugins/docker-init
  mcp: Docker MCP Plugin (Docker Inc.)
    Version:  v0.9.9
    Path:     /Users/akash/.docker/cli-plugins/docker-mcp
  model: Docker Model Runner (EXPERIMENTAL) (Docker Inc.)
    Version:  v0.1.33
    Path:     /Users/akash/.docker/cli-plugins/docker-model
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/akash/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.18.1
    Path:     /Users/akash/.docker/cli-plugins/docker-scout
WARNING: Plugin "/Users/akash/.docker/cli-plugins/docker-dev" is not valid: failed to fetch metadata: fork/exec /Users/akash/.docker/cli-plugins/docker-dev: no such file or directory

Server:
 Containers: 7
  Running: 0
  Paused: 0
  Stopped: 7
 Images: 34
 Server Version: 28.3.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 CDI spec directories:
  /etc/cdi
  /var/run/cdi
 Discovered Devices:
  cdi: docker.com/gpu=webgpu
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05044ec0a9a75232cad458027ca83437aae3f4da
 runc version: v1.2.5-0-g59923ef
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.10.14-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 8
 Total Memory: 7.26GiB
 Name: docker-desktop
 ID: a5e08603-b4f7-4767-9b3c-7b59155713a1
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=unix:///Users/akash/Library/Containers/com.docker.docker/Data/docker-cli.sock
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: DOCKER_INSECURE_NO_IPTABLES_RAW is set

### 📜 Dozzle logs are required for debugging purposes. You may need to enable debug mode. See https://dozzle.dev/guide/debugging.

2025-09-03 14:58:10.563 | {"level":"info","version":"v8.13.11","time":"2025-09-03T09:28:10Z","message":"Dozzle version v8.13.11"}
2025-09-03 14:58:10.578 | {"level":"info","version":"v8.13.11","clients":1,"time":"2025-09-03T09:28:10Z","message":"Connected to Docker"}
2025-09-03 14:58:10.579 | {"level":"info","version":"v8.13.11","time":"2025-09-03T09:28:10Z","message":"Accepting connections on :8080"}
2025-09-03 14:58:23.663 | {"level":"error","version":"v8.13.11","error":"Error response from daemon: container b2d933a3d4b4beac8a0a0025277787cc6f773ebd2cd7535637125c5bc3d503fe is not running","time":"2025-09-03T09:28:23Z","message":"error while trying to attach to container"}
2025-09-03 14:58:30.557 | {"level":"error","version":"v8.13.11","error":"websocket: close 1005 (no status)","time":"2025-09-03T09:28:30Z","message":"error while reading from ws"}
2025-09-03 14:58:30.557 | {"level":"error","version":"v8.13.11","error":"read unix @->/run/host-services/docker.proxy.sock: use of closed network connection","time":"2025-09-03T09:28:30Z","message":"error while writing to ws"}
2025-09-03 14:58:30.562 | panic: sync: negative WaitGroup counter
2025-09-03 14:58:30.562 | 
2025-09-03 14:58:30.562 | goroutine 132 [running]:
2025-09-03 14:58:30.562 | sync.(*WaitGroup).Add(0x40002fde20, 0xffffffffffffffff)
2025-09-03 14:58:30.562 | 	/usr/local/go/src/sync/waitgroup.go:118 +0x264
2025-09-03 14:58:30.562 | sync.(*WaitGroup).Done(...)
2025-09-03 14:58:30.562 | 	/usr/local/go/src/sync/waitgroup.go:156
2025-09-03 14:58:30.562 | sync.(*WaitGroup).Go.func1()
2025-09-03 14:58:30.562 | 	/usr/local/go/src/sync/waitgroup.go:240 +0x5c
2025-09-03 14:58:30.562 | created by sync.(*WaitGroup).Go in goroutine 110
2025-09-03 14:58:30.562 | 	/usr/local/go/src/sync/waitgroup.go:237 +0x70
2025-09-03 14:59:10.219 | {"level":"info","version":"v8.13.11","time":"2025-09-03T09:29:10Z","message":"Dozzle version v8.13.11"}
2025-09-03 14:59:10.238 | {"level":"info","version":"v8.13.11","clients":1,"time":"2025-09-03T09:29:10Z","message":"Connected to Docker"}
2025-09-03 14:59:10.238 | {"level":"info","version":"v8.13.11","time":"2025-09-03T09:29:10Z","message":"Accepting connections on :8080"}
2025-09-03 14:59:26.424 | {"level":"error","version":"v8.13.11","error":"websocket: close 1005 (no status)","time":"2025-09-03T09:29:26Z","message":"error while reading from ws"}
2025-09-03 14:59:26.425 | {"level":"error","version":"v8.13.11","error":"read unix @->/run/host-services/docker.proxy.sock: use of closed network connection","time":"2025-09-03T09:29:26Z","message":"error while writing to ws"}
2025-09-03 14:59:26.428 | panic: sync: negative WaitGroup counter
2025-09-03 14:59:26.428 | 
2025-09-03 14:59:26.428 | goroutine 106 [running]:
2025-09-03 14:59:26.428 | sync.(*WaitGroup).Add(0x40002c4e30, 0xffffffffffffffff)
2025-09-03 14:59:26.428 | 	/usr/local/go/src/sync/waitgroup.go:118 +0x264
2025-09-03 14:59:26.428 | sync.(*WaitGroup).Done(...)
2025-09-03 14:59:26.428 | 	/usr/local/go/src/sync/waitgroup.go:156
2025-09-03 14:59:26.428 | sync.(*WaitGroup).Go.func1()
2025-09-03 14:59:26.428 | 	/usr/local/go/src/sync/waitgroup.go:240 +0x5c
2025-09-03 14:59:26.428 | created by sync.(*WaitGroup).Go in goroutine 90
2025-09-03 14:59:26.428 | 	/usr/local/go/src/sync/waitgroup.go:237 +0x70
2025-09-03 14:59:54.492 | {"level":"info","version":"v8.13.11","time":"2025-09-03T09:29:54Z","message":"Dozzle version v8.13.11"}
2025-09-03 14:59:54.520 | {"level":"info","version":"v8.13.11","clients":1,"time":"2025-09-03T09:29:54Z","message":"Connected to Docker"}
2025-09-03 14:59:54.521 | {"level":"info","version":"v8.13.11","time":"2025-09-03T09:29:54Z","message":"Accepting connections on :8080"}
2025-09-03 15:07:09.671 | {"level":"error","version":"v8.13.11","error":"websocket: close 1005 (no status)","time":"2025-09-03T09:37:09Z","message":"error while reading from ws"}
2025-09-03 15:07:09.672 | {"level":"error","version":"v8.13.11","error":"read unix @->/run/host-services/docker.proxy.sock: use of closed network connection","time":"2025-09-03T09:37:09Z","message":"error while writing to ws"}
2025-09-03 15:07:09.674 | panic: sync: negative WaitGroup counter
2025-09-03 15:07:09.674 | 
2025-09-03 15:07:09.674 | goroutine 168 [running]:
2025-09-03 15:07:09.674 | sync.(*WaitGroup).Add(0x400039b4f0, 0xffffffffffffffff)
2025-09-03 15:07:09.675 | 	/usr/local/go/src/sync/waitgroup.go:118 +0x264
2025-09-03 15:07:09.675 | sync.(*WaitGroup).Done(...)
2025-09-03 15:07:09.675 | 	/usr/local/go/src/sync/waitgroup.go:156
2025-09-03 15:07:09.675 | sync.(*WaitGroup).Go.func1()
2025-09-03 15:07:09.675 | 	/usr/local/go/src/sync/waitgroup.go:240 +0x5c
2025-09-03 15:07:09.675 | created by sync.(*WaitGroup).Go in goroutine 166
2025-09-03 15:07:09.675 | 	/usr/local/go/src/sync/waitgroup.go:237 +0x70

### 📸 If applicable, add screenshots to help explain your bug

Image

Image

Image

### PR DESCRIPTION
**Pull request by akash-ramaswamy**
Fixes #4099 

When the attach event is triggered, the waitGroup counter is not incremented. So it panics and stops the backend when the websocket connection is closed. fixed by incrementing wg counter.

### CODE REVIEW

**Comment by amir20** [comment]
This isn't the right fix. Wg.Go already increments. You should remove the done call instead. 

I am on the phone. Will write more details soon.

File: internal/support/docker/docker_service.go [hunk 1]
```diff
@@ -121,6 +121,7 @@ func (d *DockerClientService) Attach(ctx context.Context, container container.Co
 
 	var wg sync.WaitGroup
 
+	wg.Add(1)
 	wg.Go(func() {
```
Comment (amir20) [inline internal/support/docker/docker_service.go:125]: This function already calls wg.Add.

File: internal/support/docker/docker_service.go [hunk 2]
```diff
@@ -121,6 +121,7 @@ func (d *DockerClientService) Attach(ctx context.Context, container container.Co
...
 		defer wg.Done()
```
Comment (amir20) [inline internal/support/docker/docker_service.go:126]: This is the culprit. You should remove this.

**Review by amir20 — CHANGES_REQUESTED** [review]

File: internal/support/docker/docker_service.go (hunk 2 above)
Comment (akash-ramaswamy) [reply internal/support/docker/docker_service.go:126]: yeah.. this is what I initially thought. But I was referring some articles and the modification also worked without breaking anything. Will update it.

**Comment by amir20** [comment]
That should be it. Let me know if you've tested it. I can merge.

**Comment by akash-ramaswamy** [comment]
> That should be it. Let me know if you've tested it. I can merge.

yes @amir20 . I have tested it. Attaching seems to work and the bug is also now resolved.

File: internal/support/docker/docker_service.go (hunk 2 above)
Comment (akash-ramaswamy) [reply internal/support/docker/docker_service.go]: okay.. so `w.Go` does handle few things in background (calling Add and Done) which we had to do manually before. Got it.
